export interface ApartmentData {
    id: string;
    title: string;
    location: string;
    price: string;
    rating: number;
    image: string;
    rooms: string;
    bedrooms: string;
    type: string;
  }
  
  export const apartmentData: ApartmentData[] = [
    {
      id: "1",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 5,
      image: "/housing/apartment1.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "2",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 5,
      image: "/housing/apartment2.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "3",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 3,
      image: "/housing/apartment3.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "4",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 4,
      image: "/housing/apartment4.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "5",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 5,
      image: "/housing/apartment1.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "6",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 5,
      image: "/housing/apartment2.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "7",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 3,
      image: "/housing/apartment3.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "8",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 4,
      image: "/housing/apartment4.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "9",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 5,
      image: "/housing/apartment1.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "10",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 5,
      image: "/housing/apartment2.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "11",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 3,
      image: "/housing/apartment3.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
    {
      id: "12",
      title: "Goldlux Studio Apartment",
      location: "Lagos, Nigeria",
      price: "NGN15,000",
      rating: 4,
      image: "/housing/apartment4.png",
      rooms: "3",
      bedrooms: "2",
      type: "apartment",
    },
  ];